package dev.curated.app.core.presentation.theme

import androidx.compose.ui.graphics.Color

data object ColorLight {
    val primaryLight = Color(0xFF3A608F)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFD3E3FF)
    val onPrimaryContainerLight = Color(0xFF001C39)
    val secondaryLight = Color(0xFF545F70)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFD8E3F8)
    val onSecondaryContainerLight = Color(0xFF111C2B)
    val tertiaryLight = Color(0xFF6D5677)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFF5D9FF)
    val onTertiaryContainerLight = Color(0xFF261430)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF8F9FF)
    val onBackgroundLight = Color(0xFF191C20)
    val surfaceLight = Color(0xFFF8F9FF)
    val onSurfaceLight = Color(0xFF191C20)
    val surfaceVariantLight = Color(0xFFDFE2EB)
    val onSurfaceVariantLight = Color(0xFF43474E)
    val outlineLight = Color(0xFF73777F)
    val outlineVariantLight = Color(0xFFC3C6CF)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2E3035)
    val inverseOnSurfaceLight = Color(0xFFEFF0F7)
    val inversePrimaryLight = Color(0xFFA4C9FE)
    val surfaceDimLight = Color(0xFFD8DAE0)
    val surfaceBrightLight = Color(0xFFF8F9FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF2F3FA)
    val surfaceContainerLight = Color(0xFFEDEDF4)
    val surfaceContainerHighLight = Color(0xFFE7E8EE)
    val surfaceContainerHighestLight = Color(0xFFE1E2E8)
}

data object ColorDark {
    val primaryDark = Color(0xFFFE628E)
    val onPrimaryDark = Color(0xFF1D0910)
    val primaryContainerDark = Color(0xFF5A1B32)
    val onPrimaryContainerDark = Color(0xFFFFD9E3)
    val secondaryDark = Color(0xFF1B2234)
    val onSecondaryDark = Color(0xFFF8F7FB)
    val secondaryContainerDark = Color(0xFF252D43)
    val onSecondaryContainerDark = Color(0xFFE6E9F6)
    val tertiaryDark = Color(0xFF8B9CFF)
    val onTertiaryDark = Color(0xFF10152E)
    val tertiaryContainerDark = Color(0xFF252D43)
    val onTertiaryContainerDark = Color(0xFFE6E9FF)
    val errorDark = Color(0xFFFF6F87)
    val onErrorDark = Color(0xFF31000A)
    val errorContainerDark = Color(0xFF641527)
    val onErrorContainerDark = Color(0xFFFFD9E0)
    val backgroundDark = Color(0xFF0D0F1A)
    val onBackgroundDark = Color(0xFFF8F7FB)
    val surfaceDark = Color(0xFF141826)
    val onSurfaceDark = Color(0xFFF8F7FB)
    val surfaceVariantDark = Color(0xFF1B2234)
    val onSurfaceVariantDark = Color(0xFFA2ABC2)
    val outlineDark = Color(0xFF626B82)
    val outlineVariantDark = Color(0xFF252D43)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFF8F7FB)
    val inverseOnSurfaceDark = Color(0xFF141826)
    val inversePrimaryDark = Color(0xFFBF2E5B)
    val surfaceDimDark = Color(0xFF0D0F1A)
    val surfaceBrightDark = Color(0xFF252D43)
    val surfaceContainerLowestDark = Color(0xFF0D0F1A)
    val surfaceContainerLowDark = Color(0xFF121827)
    val surfaceContainerDark = Color(0xFF141826)
    val surfaceContainerHighDark = Color(0xFF171B2B)
    val surfaceContainerHighestDark = Color(0xFF252D43)
}

val Yellow = Color(0xFFF2C94C)
